import { Conversation } from "@/lib/types/conversation"
import { getInitials } from "@/lib/utils"

/**
 * Mock data completo para conversas
 * 15 conversas com metadata rica para demonstração
 */
export const MOCK_CONVERSATIONS_DATA: Conversation[] = [
  {
    id: "1",
    contactId: "c1",
    contactName: "Maria Silva",
    contactEmail: "maria.silva@empresa.com",
    contactPhone: "11987654321",
    contactCompany: "TechCorp Brasil",
    contactPosition: "Gerente de Compras",
    contactAvatar: getInitials("Maria Silva"),
    channel: "whatsapp",
    status: "open",
    priority: "high",
    assignedTo: {
      id: "a1",
      name: "Ana Costa",
      email: "ana@empresa.com",
      avatar: "AC",
    },
    tags: ["Suporte", "Urgente"],
    sentiment: "neutral",
    slaStatus: "warning",
    lastMessage: "Oi, preciso de ajuda com meu pedido urgente!",
    unreadCount: 2,
    messageCount: 8,
    createdAt: "2026-02-26T14:30:00Z",
    updatedAt: "2026-02-26T14:45:00Z",
    lastMessageAt: "2026-02-26T14:45:00Z",
    firstResponseAt: "2026-02-26T14:35:00Z",
    messages: [],
    starred: true,
  },
  {
    id: "2",
    contactId: "c2",
    contactName: "João Pereira",
    contactEmail: "joao@exemplo.com",
    contactPhone: "21998765432",
    contactCompany: "ComércioX",
    contactAvatar: getInitials("João Pereira"),
    channel: "instagram",
    status: "pending",
    priority: "medium",
    assignedTo: {
      id: "a2",
      name: "Carlos Mendes",
      email: "carlos@empresa.com",
      avatar: "CM",
    },
    tags: ["Vendas"],
    sentiment: "positive",
    slaStatus: "ok",
    lastMessage: "Quando chega o meu produto?",
    unreadCount: 0,
    messageCount: 5,
    createdAt: "2026-02-26T13:10:00Z",
    updatedAt: "2026-02-26T14:20:00Z",
    lastMessageAt: "2026-02-26T14:20:00Z",
    firstResponseAt: "2026-02-26T13:15:00Z",
    messages: [],
  },
  {
    id: "3",
    contactId: "c3",
    contactName: "Ana Costa Oliveira",
    contactEmail: "ana.costa@test.com",
    contactCompany: "StartupHub",
    contactAvatar: getInitials("Ana Costa Oliveira"),
    channel: "whatsapp",
    status: "solved",
    priority: "low",
    assignedTo: {
      id: "a1",
      name: "Ana Costa",
      email: "ana@empresa.com",
      avatar: "AC",
    },
    tags: ["Suporte", "Resolvido"],
    sentiment: "positive",
    slaStatus: "ok",
    lastMessage: "Obrigada pelo atendimento! Problema resolvido.",
    unreadCount: 0,
    messageCount: 12,
    createdAt: "2026-02-26T10:45:00Z",
    updatedAt: "2026-02-26T11:50:00Z",
    lastMessageAt: "2026-02-26T11:50:00Z",
    firstResponseAt: "2026-02-26T10:47:00Z",
    messages: [],
  },
  {
    id: "4",
    contactId: "c4",
    contactName: "Carlos Mendes Junior",
    contactEmail: "carlos.jr@demo.com",
    contactPhone: "11976543210",
    contactCompany: "Consultoria Plus",
    contactPosition: "CEO",
    contactAvatar: getInitials("Carlos Mendes Junior"),
    channel: "iframe",
    status: "open",
    priority: "urgent",
    assignedTo: null,
    tags: ["Vendas", "VIP", "Enterprise"],
    sentiment: "neutral",
    slaStatus: "breach",
    lastMessage: "Gostaria de saber mais sobre os planos enterprise",
    unreadCount: 3,
    messageCount: 6,
    createdAt: "2026-02-26T09:20:00Z",
    updatedAt: "2026-02-26T14:40:00Z",
    lastMessageAt: "2026-02-26T14:40:00Z",
    messages: [],
    starred: true,
  },
  {
    id: "5",
    contactId: "c5",
    contactName: "Beatriz Santos",
    contactEmail: "bia@example.com",
    contactCompany: "Marketing Digital",
    contactAvatar: getInitials("Beatriz Santos"),
    channel: "email",
    status: "open",
    priority: "medium",
    assignedTo: {
      id: "a3",
      name: "Pedro Silva",
      email: "pedro@empresa.com",
      avatar: "PS",
    },
    tags: ["Suporte", "Bug"],
    sentiment: "negative",
    slaStatus: "warning",
    lastMessage: "O sistema não está funcionando corretamente",
    unreadCount: 1,
    messageCount: 4,
    createdAt: "2026-02-26T14:00:00Z",
    updatedAt: "2026-02-26T14:30:00Z",
    lastMessageAt: "2026-02-26T14:30:00Z",
    firstResponseAt: "2026-02-26T14:15:00Z",
    messages: [],
  },
  {
    id: "6",
    contactId: "c6",
    contactName: "Roberto Lima",
    contactEmail: "roberto@teste.com",
    contactPhone: "11965432109",
    contactAvatar: getInitials("Roberto Lima"),
    channel: "whatsapp",
    status: "closed",
    priority: "low",
    assignedTo: {
      id: "a1",
      name: "Ana Costa",
      email: "ana@empresa.com",
      avatar: "AC",
    },
    tags: ["Suporte"],
    sentiment: "positive",
    slaStatus: "ok",
    lastMessage: "Perfeito, muito obrigado!",
    unreadCount: 0,
    messageCount: 7,
    createdAt: "2026-02-25T16:30:00Z",
    updatedAt: "2026-02-25T17:00:00Z",
    lastMessageAt: "2026-02-25T17:00:00Z",
    firstResponseAt: "2026-02-25T16:32:00Z",
    messages: [],
  },
  {
    id: "7",
    contactId: "c7",
    contactName: "Fernanda Alves",
    contactEmail: "fernanda@email.com",
    contactCompany: "Design Studio",
    contactPosition: "Designer Lead",
    contactAvatar: getInitials("Fernanda Alves"),
    channel: "instagram",
    status: "pending",
    priority: "high",
    assignedTo: {
      id: "a2",
      name: "Carlos Mendes",
      email: "carlos@empresa.com",
      avatar: "CM",
    },
    tags: ["Vendas", "Proposta"],
    sentiment: "positive",
    slaStatus: "ok",
    lastMessage: "Aguardando proposta comercial",
    unreadCount: 0,
    messageCount: 10,
    createdAt: "2026-02-26T12:00:00Z",
    updatedAt: "2026-02-26T13:30:00Z",
    lastMessageAt: "2026-02-26T13:30:00Z",
    firstResponseAt: "2026-02-26T12:05:00Z",
    messages: [],
  },
  {
    id: "8",
    contactId: "c8",
    contactName: "Paulo Rodrigues",
    contactEmail: "paulo.r@company.com",
    contactPhone: "21987651234",
    contactCompany: "Tech Innovations",
    contactAvatar: getInitials("Paulo Rodrigues"),
    channel: "whatsapp",
    status: "open",
    priority: "medium",
    assignedTo: {
      id: "a3",
      name: "Pedro Silva",
      email: "pedro@empresa.com",
      avatar: "PS",
    },
    tags: ["Suporte", "Dúvida"],
    sentiment: "neutral",
    slaStatus: "ok",
    lastMessage: "Como faço para exportar os relatórios?",
    unreadCount: 1,
    messageCount: 3,
    createdAt: "2026-02-26T14:15:00Z",
    updatedAt: "2026-02-26T14:45:00Z",
    lastMessageAt: "2026-02-26T14:45:00Z",
    firstResponseAt: "2026-02-26T14:20:00Z",
    messages: [],
  },
  {
    id: "9",
    contactId: "c9",
    contactName: "Juliana Martins",
    contactEmail: "ju.martins@example.com",
    contactCompany: "E-commerce Brasil",
    contactPosition: "Product Manager",
    contactAvatar: getInitials("Juliana Martins"),
    channel: "iframe",
    status: "open",
    priority: "low",
    assignedTo: null,
    tags: ["Feedback", "Feature Request"],
    sentiment: "positive",
    slaStatus: "ok",
    lastMessage: "Vocês tem planos de adicionar integração com...",
    unreadCount: 1,
    messageCount: 2,
    createdAt: "2026-02-26T13:45:00Z",
    updatedAt: "2026-02-26T14:10:00Z",
    lastMessageAt: " 2026-02-26T14:10:00Z",
    messages: [],
  },
  {
    id: "10",
    contactId: "c10",
    contactName: "Ricardo Souza",
    contactEmail: "ricardo@test.com",
    contactPhone: "11954321098",
    contactAvatar: getInitials("Ricardo Souza"),
    channel: "sms",
    status: "pending",
    priority: "medium",
    assignedTo: {
      id: "a1",
      name: "Ana Costa",
      email: "ana@empresa.com",
      avatar: "AC",
    },
    tags: ["Suporte"],
    sentiment: "neutral",
    slaStatus: "warning",
    lastMessage: "Preciso falar com um supervisor",
    unreadCount: 0,
    messageCount: 6,
    createdAt: "2026-02-26T11:30:00Z",
    updatedAt: "2026-02-26T12:50:00Z",
    lastMessageAt: "2026-02-26T12:50:00Z",
    firstResponseAt: "2026-02-26T11:40:00Z",
    messages: [],
  },
]
